yii/notejam/models/Pad.php
<?php
namespace app\models;

use Yii;

/**
 * User model
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 */
class Pad extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            ['name', 'required'],
        ];
    }

    /**
     * @return string the name of the table associated with
     *         this ActiveRecord class.
     */
    public static function tableName()
    {
        return 'pads';
    }

    /**
     * Get user
     *
     * @return app\models\User
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * Get notes
     */
    public function getNotes()
    {
        return $this->hasMany(Note::className(), ['pad_id' => 'id']);
    }
}

yii/notejam/controllers/NoteController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\Note;
use app\controllers\BaseController;

class NoteController extends BaseController
{
    public $layout = 'app';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'list' => ['get'],
                    'create' => ['get', 'post'],
                    'edit' => ['get', 'post'],
                    'delete' => ['get', 'post'],
                    'view' => ['get'],
                    'error' => ['get'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    public function actionList()
    {
        $notes = Note::find()
            ->where(['user_id' => Yii::$app->user->identity->getId()])
            ->orderBy($this->getOrderParam())
            ->all();

        return $this->render('list', ['notes' => $notes]);
    }

    public function actionCreate($pad)
    {
        $note = new Note();
        $note->pad_id = $pad;

        if ($note->load(Yii::$app->request->post()) && $note->validate()) {
            /** @var User $user */
            $user = Yii::$app->user->identity;
            $user->link('notes', $note);
            Yii::$app->session->setFlash(
                'success', 'Note is successfully created.'
            );
            return $this->redirect('note/list');
        }
        return $this->render('create', [
            'note' => $note,
        ]);
    }

    public function actionEdit($id)
    {
        $note = $this->getNote($id);

        if ($note->load(Yii::$app->request->post()) && $note->validate()) {
            /** @var User $user */
            $user = Yii::$app->user->identity;
            $user->link('notes', $note);
            Yii::$app->session->setFlash(
                'success', 'Note is successfully updated.'
            );
            return $this->redirect(['note/edit', 'id' => $note->id]);
        }
        return $this->render('edit', [
            'note' => $note,
        ]);
    }

    public function actionView($id)
    {
        $note = $this->getNote($id);

        return $this->render('view', [
            'note' => $note,
        ]);
    }

    public function actionDelete($id)
    {
        $note = $this->getNote($id);

        if (Yii::$app->request->getIsPost()) {
            $note->delete();
            Yii::$app->session->setFlash(
                'success', 'Note is successfully deleted.'
            );
            return $this->redirect('note/list');
        }
        return $this->render('delete', [
            'note' => $note,
        ]);
    }

    /**
     * Get note or raise 404
     *
     * @param integer $id note id
     * @return Note
     * @throws \yii\web\HttpException
     */
    private function getNote($id)
    {
        $note = Note::findOne([
            'id' => $id,
            'user_id' => Yii::$app->user->identity->getId(),
        ]);
        if (!$note) {
            throw new \yii\web\HttpException(404, 'Not Found');
        }
        return $note;
    }
}

yii/notejam/controllers/PadController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\Pad;

class PadController extends BaseController
{
    public $layout = 'app';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'create' => ['get', 'post'],
                    'edit' => ['get', 'post'],
                    'delete' => ['get', 'post'],
                ],
            ],
        ];
    }

    public function actionCreate()
    {
        $pad = new Pad();

        if ($pad->load(Yii::$app->request->post()) && $pad->validate()) {
            /** @var User $user */
            $user = Yii::$app->user->identity;
            $user->link('pads', $pad);
            Yii::$app->session->setFlash(
                'success', 'Pad is successfully created.'
            );
            return $this->redirect('note/list');
        }
        return $this->render('create', [
            'pad' => $pad,
        ]);
    }

    public function actionEdit($id)
    {
        $pad = $this->getPad($id);

        if ($pad->load(Yii::$app->request->post()) && $pad->validate()) {
            $pad->save();
            Yii::$app->session->setFlash(
                'success', 'Pad is successfully updated.'
            );
            return $this->redirect('note/list');
        }
        return $this->render('edit', [
            'pad' => $pad,
        ]);
    }

    public function actionDelete($id)
    {
        $pad = $this->getPad($id);

        if (Yii::$app->request->getIsPost()) {
            $pad->delete();
            Yii::$app->session->setFlash(
                'success', 'Pad is successfully deleted.'
            );
            return $this->redirect('note/list');
        }
        return $this->render('delete', [
            'pad' => $pad,
        ]);
    }

    public function actionView($id)
    {
        $pad = $this->getPad($id);
        $notes = $pad->getNotes()->orderBy($this->getOrderParam())->all();
        return $this->render('view', ['pad' => $pad, 'notes' => $notes]);
    }

    /**
     * Get pad or raise 404
     *
     * @param integer $id pad id
     * @return Pad
     * @throws \yii\web\HttpException
     */
    private function getPad($id)
    {
        $pad = Pad::findOne([
            'id' => $id,
            'user_id' => Yii::$app->user->identity->getId(),
        ]);
        if (!$pad) {
            throw new \yii\web\HttpException(404, 'Not Found');
        }
        return $pad;
    }
}

yii/notejam/views/pad/create.php
<?php
$this->title = 'New pad';
?>

<?= $this->render('form', ['pad' => $pad]) ?>

yii/notejam/views/pad/delete.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
$this->title = $pad->name;
?>

<?php $form = ActiveForm::begin(); ?>

    <p>Are you sure you want to delete <?= Html::encode($this->title) ?>?</p>
    <?= Html::submitButton('Yes, delete I want to delete it', ['class' => 'red']) ?>&nbsp;
    <a href="<?= Url::toRoute(['pad/edit', 'id' => $pad->id]); ?>">Cancel</a>

<?php ActiveForm::end(); ?>

yii/notejam/views/pad/edit.php
<?php
$this->title = $pad->name;
?>

<?= $this->render('form', ['pad' => $pad]) ?>

yii/notejam/views/pad/form.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
?>

<?php $form = ActiveForm::begin([
    'fieldConfig' => [
        'template' => "{label}{input}",
    ],
]); ?>

<?= $form->field($pad, 'name') ?>
<?= $this->render('/partials/errors', ['model' => $pad, 'field' => 'name']) ?>

<?= Html::submitButton('Save') ?>
<p>
    <a href="<?= Url::toRoute(['pad/delete', 'id' => $pad->id])?>" class="red">Delete pad</a>
</p>

<?php ActiveForm::end(); ?>

yii/notejam/views/pad/view.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
$this->title = $pad->name . ' (' . count($notes) . ')';
?>
<?php if ($notes): ?>
  <table class="notes">
    <tr>
      <th class="note">Note <a href="<?= Url::toRoute(['pad/view', 'id' => $pad->id, 'order' => '-name']) ?>" class="sort_arrow" >&uarr;</a><a href="<?= Url::toRoute(['pad/view', 'id' => $pad->id, 'order' => 'name']) ?>" class="sort_arrow" >&darr;</a></th>
      <th class="date">Last modified <a href="<?= Url::toRoute(['pad/view', 'id' => $pad->id, 'order' => '-updated_at']) ?>" class="sort_arrow" >&uarr;</a><a href="<?= Url::toRoute(['pad/view', 'id' => $pad->id, 'order' => 'updated_at']) ?>" class="sort_arrow" >&darr;</a></th>
    </tr>
    <?php foreach($notes as $note): ?>
        <tr>
          <td><a href="<?= Url::toRoute(['note/view', 'id' => $note->id]) ?>"><?= Html::encode($note->name); ?></a></td>
          <td class="hidden-text date"><?= $note->getSmartDate(); ?></td>
        </tr>
    <?php endforeach; ?>
  </table>
<?php else: ?>
  <p class="empty">Create first note in the pad.</p>
<?php endif; ?>
<a href="<?= Url::toRoute(['note/create', 'pad' => $pad->id])?>" class="button">New note</a>&nbsp;
<a href="<?= Url::toRoute(['pad/edit', 'id' => $pad->id])?>">Pad settings</a>