yii/notejam/controllers/PadController.php
<?php

namespace app\controllers;

use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\Pad;

class PadController extends BaseController
{
    public $layout = 'app';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'create' => ['get', 'post'],
                    'edit' => ['get', 'post'],
                    'delete' => ['get', 'post'],
                ],
            ],
        ];
    }

    public function actionCreate()
    {
        $pad = new Pad();

        if ($pad->load(Yii::$app->request->post()) && $pad->validate()) {
            /** @var User $user */
            $user = Yii::$app->user->identity;
            $user->link('pads', $pad);
            Yii::$app->session->setFlash(
                'success', 'Pad is successfully created.'
            );
            return $this->redirect('note/list');
        }
        return $this->render('create', [
            'pad' => $pad,
        ]);
    }

    public function actionEdit($id)
    {
        $pad = $this->getPad($id);

        if ($pad->load(Yii::$app->request->post()) && $pad->validate()) {
            $pad->save();
            Yii::$app->session->setFlash(
                'success', 'Pad is successfully updated.'
            );
            return $this->redirect('note/list');
        }
        return $this->render('edit', [
            'pad' => $pad,
        ]);
    }

    public function actionDelete($id)
    {
        $pad = $this->getPad($id);

        if (Yii::$app->request->getIsPost()) {
            $pad->delete();
            Yii::$app->session->setFlash(
                'success', 'Pad is successfully deleted.'
            );
            return $this->redirect('note/list');
        }
        return $this->render('delete', [
            'pad' => $pad,
        ]);
    }

    public function actionView($id)
    {
        $pad = $this->getPad($id);
        $notes = $pad->getNotes()->orderBy($this->getOrderParam())->all();
        return $this->render('view', ['pad' => $pad, 'notes' => $notes]);
    }

    /**
     * Get pad or raise 404
     *
     * @param integer $id pad id
     * @return Pad
     * @throws \yii\web\HttpException
     */
    private function getPad($id)
    {
        $pad = Pad::findOne([
            'id' => $id,
            'user_id' => Yii::$app->user->identity->getId(),
        ]);
        if (!$pad) {
            throw new \yii\web\HttpException(404, 'Not Found');
        }
        return $pad;
    }
}

yii/notejam/controllers/UserController.php
<?php

namespace app\controllers;

use app\models\ChangePassword;
use app\models\ForgotPassword;
use app\models\SigninForm;
use app\models\SignupForm;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;

class UserController extends Controller
{
    public $layout = 'user';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'settings'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['get'],
                    'settings' => ['get', 'post'],
                    'signin' => ['get', 'post'],
                    'signup' => ['get', 'post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }

    public function actionSettings()
    {
        $model = new ChangePassword();
        if ($model->load(Yii::$app->request->post()) &&
            $model->changePassword(Yii::$app->user->identity)
        ) {
            Yii::$app->session->setFlash(
                'success', 'Password is successfully changed.'
            );
            return $this->goHome();
        } else {
            return $this->render('settings', [
                'model' => $model,
            ]);
        }
    }

    public function actionForgotPassword()
    {
        $model = new ForgotPassword();
        if ($model->load(Yii::$app->request->post()) &&
            $model->resetPassword()
        ) {
            Yii::$app->session->setFlash(
                'success', 'New password sent. Check your inbox.'
            );
            return $this->redirect('signin');
        } else {
            return $this->render('forgot-password', [
                'model' => $model,
            ]);
        }
    }


    public function actionSignin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new SigninForm();
        if ($model->load(Yii::$app->request->post()) && $model->signin()) {
            return $this->goHome();
        } else {
            return $this->render('signin', [
                'model' => $model,
            ]);
        }
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                Yii::$app->session->setFlash(
                    'success', 'Account is created. Now you can sign in.'
                );
                return $this->goHome();
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionSignout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
}

yii/notejam/views/layouts/app.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>

<?php $this->beginBlock('pads'); ?>
    <div class="three columns">
      <h4 id="logo">My pads</h4>
          <nav>
              <?php if (Yii::$app->user->identity->pads): ?>
                  <ul>
                    <?php foreach(Yii::$app->user->identity->pads as $pad): ?>
                        <li><a href="<?= Url::toRoute(['pad/view', 'id' => $pad->id])?>"><?= Html::encode($pad->name) ?></a></li>
                    <?php endforeach; ?>
                  </ul>
              <?php else: ?>
                   <p class="empty">No pads</p>
              <?php endif; ?>
              <hr />
              <a href="<?= Url::toRoute('pad/create'); ?>">New pad</a>
          </nav>
    </div>
<?php $this->endBlock(); ?>

<?php $this->beginContent('@app/views/layouts/base.php'); ?>
    <div class="thirteen columns content-area">
      <div class="alert-area">
        <?php if (Yii::$app->session->hasFlash('success')): ?>
            <div class="alert alert-success"><?= Yii::$app->session->getFlash('success') ?></div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('error')): ?>
            <div class="alert alert-error"><?= Yii::$app->session->getFlash('success') ?></div>
        <?php endif; ?>
      </div>
      <?= $content ?>
    </div>
<?php $this->endContent(); ?>

yii/notejam/views/layouts/base.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>

<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

	<!-- Basic Page Needs
  ================================================== -->
	<meta charset="utf-8">
    <title><?= Html::encode($this->title) ?></title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Metas
  ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  ================================================== -->
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/skeleton/1.2/base.min.css">
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/skeleton/1.2/skeleton.min.css">
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/skeleton/1.2/layout.css">
	<link rel="stylesheet" href="/css/style.css">

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
  <div class="container">
    <div class="sixteen columns">
      <div class="sign-in-out-block">
        <?php if (Yii::$app->user->isGuest): ?>
            <a href="<?= Url::toRoute('user/signin') ?>">Sign in</a>&nbsp;&nbsp;&nbsp;<a href="<?= Url::toRoute('user/signup') ?>">Sign up</a>
        <?php else: ?>
            <?= Html::encode(Yii::$app->user->identity->email) ?>:&nbsp; <a href="<?= Url::toRoute('user/settings') ?>">Account settings</a>&nbsp;&nbsp;&nbsp;<a href="<?= Url::toRoute('user/signout') ?>">Sign out</a>
        <?php endif; ?>
      </div>
    </div>
    <div class="sixteen columns">
      <h1 class="bold-header">
          <a href="<?= Url::toRoute('note/list'); ?>" class="header">note<span class="jam">jam: </span></a> <span><?= Html::encode($this->title) ?></span>
      </h1>
    </div>
    <?= $this->blocks['pads'] ?>

    <?= $content ?>

    <hr class="footer" />
    <div class="footer">
      <div>Notejam: <strong>Yii</strong> application</div>
      <div><a href="https://github.com/komarserjio/notejam">Github</a>, <a href="https://twitter.com/komarserjio">Twitter</a>, created by <a href="https://github.com/komarserjio/">Serhii Komar</a></div>
    </div>
  </div><!-- container -->
</body>
</html>

yii/notejam/views/layouts/user.php
<?php $this->beginBlock('pads'); ?>
<?php $this->endBlock(); ?>

<?php $this->beginContent('@app/views/layouts/base.php'); ?>
    <div class="sixteen columns content-area">
      <div class="alert-area">
        <?php if (Yii::$app->session->hasFlash('success')): ?>
            <div class="alert alert-success"><?= Yii::$app->session->getFlash('success') ?></div>
        <?php endif; ?>
        <?php if (Yii::$app->session->hasFlash('error')): ?>
            <div class="alert alert-error"><?= Yii::$app->session->getFlash('success') ?></div>
        <?php endif; ?>
      </div>
      <?= $content ?>
    </div>
<?php $this->endContent(); ?>